# -*- coding: utf-8 -*-
"""star1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PwWrqoz4VpRTQ_tfetpQWvPI73SGNj6M
"""

a=input("숫자를 입력하세요")
b=int(a)
for i  in range(1,b+1):
  for i  in range(1,i):
    print("*", end='')
  print("")

